### ISSUE TITLE
Justificativa para o uso de C#

### ISSUE THREAD

**Issue by Rubenscsantos** [Infnet-SJ90/desktop-api#2]
Justifique a escolha da tecnologia utilizada para o desenvolvimento do projeto e compare com duas outras opções que poderiam ser utilizadas.

**Comment by lcsnoblat** [comment]
Algumas justificativas para o uso de C# são: utilizando .net core fornece agilidade na hora de desenvolver combinado com ótima performance, possui uma boa integração com a IDE, e ainda possui uma ótima documentação .

Em questão de outras opções, temos: Spring MVC, que possui uma grande quantidade de usuários e por esse motivo tem uma boa comunidade oque pode ser muito útil em questão de tutoriais e depuração.

Outra opção seria utilizar Django rest framework que roda em python, o Django por si só é incrivelmente rápido e simples de ser usado oque traria agilidade para diversos aspectos e vale a pena ser estudado.
