### ISSUE TITLE
Vantagens do uso de C# para o projeto

### ISSUE THREAD

**Issue by Rubenscsantos** [Infnet-SJ90/desktop-api#3]
Enumere uma lista de pelo menos 3 prós e contras

**Comment by lcsnoblat** [comment]
PROS:

1 - Async-oriented

2 - Sem necessidade de integrar outras tecnologias para o desenvolvimento.

3 - Boa Integração com a IDE

CONS: 

1 - Relativamente novo se comparado a outras opções, então possui alguns pequenos bugs

2 - A IDE é um pouco pesada

3 - Alguns serviços podem sair caros.
