### ISSUE TITLE
Completar a Modelagem de Domínio usando UML padrão com o caso de uso gerenciamento de recursos

### ISSUE THREAD

**Issue by lcsnoblat** [Infnet-SJ90/desktop-api#6]

**Comment by Rubenscsantos** [comment]
https://www.draw.io/?state=%7B%22ids%22:%5B%221ZYhl7S19m5BlPrLKAsTbt7ZdL7tSbZ7U%22%5D,%22action%22:%22open%22,%22userId%22:%22{userId}%22%7D#G1ZYhl7S19m5BlPrLKAsTbt7ZdL7tSbZ7U

**Comment by Rubenscsantos** [comment]
![image](https://user-images.githubusercontent.com/12104162/43054488-3486f15a-8e08-11e8-944d-3de761559617.png)
